### ISSUE TITLE
No devices found.

### ISSUE THREAD

**Issue by v-alisei** [TiePie/python-libtiepie#5]
Hello. I have an hs5 usb oscilloscope. Multi channel software see it. The device is seen in windows device manager. But libtiepie can't see it. please help me.

**Comment by v-alisei** [comment]
oh. Okay. I reinstalled drivers, restarted pc, installed 0.9.7 and it worked)

**Comment by tandeitnik** [comment]
I'm having this issue of 'no devices found' for weeks and I can't solve it. Tried reinstalling the drivers, using different python environments, nothing seems to solve the problem! I'm on a Windows 10 PC.

**Comment by jsp9549** [comment]
I had the same issue, solved it by downgrading the driver to:
[TiePie DriverInstall-USB_v8.1.9.zip](https://github.com/TiePie/python-libtiepie/files/11208914/TiePie.DriverInstall-USB_v8.1.9.zip)
